### ISSUE TITLE
TabText not displaying correctly when loading information from Cache

### ISSUE THREAD

**Issue by lennart-bader** [MyTFG/mytfg-vplan-app#1]
Beim Laden der VPlan-Daten aus dem Cache werden die Tab-Titel nicht korrekt gesetzt.

Erst bei einem "Reload" (Swipe2Refresh) oder dem Starten einer Suche wird der Titel korrekt gesetzt.

Gibt auch einen Eintrag auf stackoverflow dazu von mir - ohne Antwort :cry:

**Comment by rleh** [comment]
> Gibt auch einen Eintrag auf stackoverflow dazu von mir - ohne Antwort 😢

Link?

**Comment by lennart-bader** [comment]
http://stackoverflow.com/questions/41388068/android-tablayout-tab-text-truncated

**Comment by lennart-bader** [comment]
Mit 0.5.3b "behoben" - Problem tritt auf, wenn aus dem Cache geladen wird, da das Callback und die Aktualisierung der Titel irgendwie einer RunCondition unterliegen. Habe jetzt 10ms Verzögerung eingebaut.
