### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by lennart-bader** [MyTFG/mytfg-vplan-app#11]
Damit alle (halb) versteckten Funktionen bekannt werden und die App benutzerfreundlich ist, sollte beim ersten Start ein kurzes "Tutorial" eingeblendet werden, wo man draufdrücken kann und was das dann tolles macht. Bei vielen Apps wird das ja ganz nett gemacht mit diversen Overlays, welche die relavanten Buttons einkreisen etc.

Oder gibt es da andere Meinungen?

**Comment by rleh** [comment]
Sehr gute Idee :+1:

**Comment by lennart-bader** [comment]
Ist mit dem "ShowCaseManager" und dem "CustomViewTarget" enthalten.
Wird in VPlan und Start bereits angezeigt.
