### ISSUE TITLE
Vorschläge

### ISSUE THREAD

**Issue by HanEmile** [MyTFG/mytfg-vplan-app#28]
Also, an sich find ich die App super, hab nur so ein paar sachen die anders sein könnten:

- Das Logo
    - im G von TFG ist ein Kreuz eingebaut, der JC hängt da dann schräg
    - macht es einfach fett **TFG**

- Der V-PLAN macht es einfach schlicht:
    - ursprünglicher Raum
    - neuer Raum
    - kommentare
    - man sollte auf den ersten blick sehen soll was los ist

- Die Icons:
    - müsst ihr eigene machen? Wenn nicht, guckt euch einfach mal die [Material Icons](https://material.io/icons/) an

Das wars aber auch ;D

**Comment by lennart-bader** [comment]
Der VPlan enthält exakt die Informationen, welche du oben auflistest?! Ggf. werden wir nach Rücksprache mit Herrn Meyer das Layout nochmals anpassen. Oder mit dem Kommentar gemeint, dass das Layout, welches beim Klicken auf einen Eintrag erscheint, dauerhaft genutzt werden sollte?

Bzgl. der Icons: Die werden noch überarbeitet und vorallem in einheitliche Farben geändert. Generall entsprechen die Icons jedoch alle dem Material Design, welches Grundlage der gesamten App ist.

**Comment by Turakar** [comment]
Gibt es hier noch Ergänzungen oder sollen wir den Issue schließen?

**Comment by lennart-bader** [comment]
Also Icons haben wir ersetzt, das App-Icon wurde aus mehreren Alternativen so gewählt und der VPlan erfüllt ja bereits die gewünschten Anzeigeeigenschaften. Ich schließe mal.
