### ISSUE TITLE
Toolbar wird nicht wieder angezeigt beim Suchen

### ISSUE THREAD

**Issue by Turakar** [MyTFG/mytfg-vplan-app#30]
Im VPlan oder bei den News wird die Suchleiste nicht angezeigt, wenn die Toolbar versteckt ist.

Erzeugt mit:
1. Runter scrollen bis die Toolbar versteckt ist
2. Dann hoch bis der Suchknopf wieder da ist
3. Dann suchen drücken

**Comment by lennart-bader** [comment]
Ungut - wie sieht es denn generell aus: Ist das mit der sich versteckenden Toolbar gut? Oder soll das eh wieder weg? (Dann wäre auch der Issue hier hinfällig)

**Comment by Turakar** [comment]
Habe mal rumgefragt, die wurde sowohl positiv als auch negativ aufgenommen. Ich persönlich finde das Verstecken störend, weil auch Bedienelemente verloren gehen, aber ich habe auch einen 5" Bildschirm.

**Comment by lennart-bader** [comment]
Ok. Dann würde ich vorschlagen:

* Ich setze das als Option in die Einstellungen, dass man das deaktivieren kann
* Wenn man auf suchen drückt, wird das ausgeklappt (hoffentlich klappt das^^)

**Comment by Turakar** [comment]
Klingt gut

**Comment by lennart-bader** [comment]
Siehe #35
