### ISSUE TITLE
Push Notifications die zweite

### ISSUE THREAD

**Issue by lennart-bader** [MyTFG/mytfg-vplan-app#9]
Push Benachrichtigungen für den VPlan? 
* Versionierung des VPlans in MyTFG bereits eingeführt
* Änderungen könnten erkannt werden
* Diesmal richtig! Ohne Crashs

**Comment by rleh** [comment]
Wollen wir Firebase (ehem. GCM) nutzen?
Oder Websockets? Oder periodisches Pollen?

GCM setzt Google Services voraus, das finde ich blöd (als einzige Lösung).

Wie wird das in iOS implementiert?

**Comment by lennart-bader** [comment]
iOS nutzt auch einen Apple Dienst (quasi GCM / Firebase). Ich bin eher dafür, dass wir uns auf Firebase verlassen und im Zweifel eine Option für periodisches (stündliches?) pollen aktivieren - die meisten Eltern und Schüler werden aber bestimmt Google Services haben, oder?!

Websockets sind bestimmt (unnötig) kompliziert / Mehraufwand

**Comment by lennart-bader** [comment]
Also Firebase scheint mit allem kompatibel zu sein - PlayServices werden dennoch benötigt. Wer das nicht hat, kann dann eben keine Benachrichtigungen nutzen...

https://firebase.google.com/docs/cloud-messaging/

**Comment by Turakar** [comment]
Die Signal-Lösung um Firebase und Websockets zu kombinieren war, über Firebase leere Nachrichten zu schicken, die dann beim Empfangen eine Anfrage des Clients am Server auslösen, wo er sich dann die Daten holt. Das löst auch das Problem, dass man die Daten Firebase und dem Apple-Dienst wahrscheinlich in unterschiedlicher Form zugänglich machen muss. Ich würde tatsächlich erst mit Google-Diensten implementieren, um dann nachher eventuell die Websockets hinzuzufügen.

**Comment by Turakar** [comment]
Und die Crashs kamen von unserem Context-Handling. Den darf man nicht statisch in eine Variable schreiben, der ändert sich nämlich (zB Service und Activity).

**Comment by lennart-bader** [comment]
Ja, die Crashs kamen tatsächlich daher - war ja eigentlich schon bekannt, hat nur nie jemand gefixt :smile: 

Leere Nachrichten sind nicht unbedingt notwendig, etwas "präziser" ist schon ok. Aber nur Hinweise, dass sich ggf. irgendwas geändert hat, keine eigentlichen Inhalte. Firebase ist theoretisch auch mit Apple / iOS kompatibel. Das Versenden von Daten an beide Dienste ist nicht sonderlich schwierig (teilweise bereits in MyTFG implementiert). 

Ggf. wollte Jakob das aber gar nicht implementieren, sondern nur Polling machen...

**Comment by Turakar** [comment]
Polling zieht halt an Batterie und Volumen, deswegen hat sich Whispersystems lange geweigert, das umzusetzen.

**Comment by lennart-bader** [comment]
Stimmt schon - kommt aber auf das entsprechende Pollinginterval an. Wenn man das jede Stunde macht, ist das nicht sehr relevant.

Ich bin aber auch eher für Push :wink: 

Die "Basisklassen" habe ich bereits teilweise implementiert - sind auch schon im Master.

**Comment by lennart-bader** [comment]
Ich habe firebase eingefügt. Für vplan Änderungen kommen jetzt Benachrichtigungen. Ist aber noch nicht in der play store Version, da ich das noch etwas verbessern muss.

**Comment by lennart-bader** [comment]
Seit 0.6.4b eingefügt
